### PR TITLE
Update to use Unified API

### PR DESCRIPTION
**Pull request by HofmaDresu**
I updated the binding to use the new Unified API and for compatibility with x64 devices. The App Store requires that new apps are compatible with x64 devices and will soon require app updates to be compatible. 

There is one breaking change from 0.1: SWRevealViewController removed the “SWRevealViewControllerSegue” and replaced it with “SWRevealViewControllerSegueSetController”. If someone updates from 0.1 to 0.2 of this library, they need to adjust their Segues to match this change.

### CODE REVIEW

**Comment by Vandborg** [comment]
Thanks @HofmaDresu!

@Viv-Rajkumar can you take a look on this? I still don't have a license for Xamarin. :)

**Comment by martijn00** [comment]
Any news on this?

**Comment by Vandborg** [comment]
Hmm nope, I guess this is dead since I still don't have a xamarin license. But I'll just accept the pull request, but I can't say anything about if it works.

**Comment by HofmaDresu** [comment]
Thanks @Vandborg! I've been using it in a production app for a while now and haven't seen any issues, so there's a nice sample size of 1 developer

**Comment by Vandborg** [comment]
Hehe great ;) Perhaps you want to take over this project?

**Comment by HofmaDresu** [comment]
I certainly could if you don't want to hold it anymore. I'd be making pull requests if there are ever new, breaking changes in the iOS systems again anyways

**Pull request merged**
